# Generated by Django 4.2.10 on 2024-04-14 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContabilidadFisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "proceso_actual",
                    models.CharField(
                        choices=[
                            ("AD", "Administrador"),
                            ("AL", "Almacenista"),
                            ("FI", "Finalizado"),
                        ],
                        default="AL",
                        max_length=2,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PR", "En Proceso"),
                            ("CO", "Contabilizado"),
                            ("AP", "Aprobado"),
                            ("RE", "Rechazado"),
                        ],
                        default="PR",
                        max_length=2,
                    ),
                ),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contabilidad Fisica",
                "verbose_name_plural": "Contabilidades Fisica",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="DetContabilidadFisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_contada", models.IntegerField(default=0)),
                ("cantidad_inventario", models.IntegerField(default=0)),
                (
                    "contabilidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle",
                        to="movimientos.contabilidadfisica",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle Contabilidad Fisica",
                "verbose_name_plural": "Detalle Contabilidades Fisica",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="TipoMov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "operacion",
                    models.CharField(
                        choices=[("+", "Suma"), ("-", "Resta")], max_length=2
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Movimiento",
                "verbose_name_plural": "Tipos de Movimientos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_soli", models.DateField()),
                ("fecha_en_espera", models.DateField(blank=True, null=True)),
                ("descripcion", models.TextField()),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
                ("recipe", models.ImageField(upload_to="recipes/")),
                (
                    "proceso_actual",
                    models.CharField(
                        choices=[
                            ("AD", "Administrador"),
                            ("AL", "Almacenista"),
                            ("AT", "Atención al Cliente"),
                            ("FI", "Finalizado"),
                        ],
                        default="AT",
                        max_length=2,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PR", "En Proceso"),
                            ("DV", "Datos Verificados"),
                            ("AP", "Aprobado"),
                            ("EE", "En Espera de Entrega"),
                            ("NR", "Paciente no retiró"),
                            ("ET", "Entregado"),
                            ("RE", "Rechazado"),
                        ],
                        default="PR",
                        max_length=2,
                    ),
                ),
                (
                    "tipo_solicitud",
                    models.CharField(
                        choices=[("ON", "En línea"), ("PR", "Presencial")], max_length=2
                    ),
                ),
                (
                    "beneficiado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.beneficiado",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Medicamento",
                "verbose_name_plural": "Solicitud de Medicamentos",
                "ordering": ["fecha_soli"],
            },
        ),
        migrations.CreateModel(
            name="Jornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encargados", models.TextField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
                ("fecha_solicitud", models.DateField(blank=True, null=True)),
                ("fecha_jornada", models.DateField(blank=True, null=True)),
                (
                    "proceso_actual",
                    models.CharField(
                        choices=[
                            ("AD", "Administrador"),
                            ("AL", "Almacenista"),
                            ("FI", "Finalizado"),
                        ],
                        default="AD",
                        max_length=2,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PR", "En Proceso"),
                            ("AP", "Aprobado"),
                            ("RE", "Rechazado"),
                            ("ET", "Entregado"),
                        ],
                        default="PR",
                        max_length=2,
                    ),
                ),
                ("comunidad", models.ManyToManyField(to="entidades.comunidad")),
                (
                    "jefe_comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jornada",
                "verbose_name_plural": "Jornadas",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="InventarioContFisica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_contada", models.IntegerField(default=0)),
                ("cantidad_inventario", models.IntegerField(default=0)),
                (
                    "detcontabilidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_inventario",
                        to="movimientos.detcontabilidadfisica",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario Contabilidad Fisica",
                "verbose_name_plural": "Inventario Contabilidades Fisica",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                (
                    "tipo_ingreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movimientos.tipomov",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingresos",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_mov", models.DateField(auto_now_add=True)),
                ("cantidad", models.IntegerField()),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="entidades.perfil",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial",
                        to="inventario.inventario",
                    ),
                ),
                (
                    "tipo_mov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movimientos.tipomov",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Inventario",
                "verbose_name_plural": "Movimientos de Inventario",
                "ordering": ["-pk"],
            },
        ),
        migrations.CreateModel(
            name="Egreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                (
                    "tipo_egreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="movimientos.tipomov",
                    ),
                ),
            ],
            options={
                "verbose_name": "Egreso",
                "verbose_name_plural": "Egresos",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="DetalleSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cant_solicitada", models.IntegerField(default=1)),
                ("cant_entregada", models.IntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle",
                        to="movimientos.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de solicitud",
                "verbose_name_plural": "Detalle de solicitudes",
                "ordering": ["pk"],
                "unique_together": {("solicitud", "producto")},
            },
        ),
        migrations.CreateModel(
            name="DetalleJornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cant_solicitada", models.IntegerField(default=1)),
                ("cant_aprobada", models.IntegerField(default=0)),
                (
                    "jornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle",
                        to="movimientos.jornada",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Jornada",
                "verbose_name_plural": "Detalle de Jornadas",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="DetalleIngreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("lote", models.CharField(max_length=50)),
                ("f_vencimiento", models.DateField()),
                (
                    "ingreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle",
                        to="movimientos.ingreso",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de ingreso",
                "verbose_name_plural": "Detalles de ingresos",
            },
        ),
        migrations.CreateModel(
            name="DetalleEgreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "egreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle",
                        to="movimientos.egreso",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de egreso",
                "verbose_name_plural": "Detalles de egreso",
            },
        ),
        migrations.CreateModel(
            name="DetalleIventarioSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=0)),
                (
                    "detsolicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_inventario",
                        to="movimientos.detallesolicitud",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de inventario solicitado",
                "verbose_name_plural": "Detalles de inventario solicitados",
                "ordering": ["pk"],
                "unique_together": {("detsolicitud", "inventario")},
            },
        ),
        migrations.CreateModel(
            name="DetalleIventarioJornada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=0)),
                (
                    "detjornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_inventario",
                        to="movimientos.detallejornada",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventario.inventario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de inventario jornada",
                "verbose_name_plural": "Detalles de inventario jornadas",
                "ordering": ["pk"],
                "unique_together": {("detjornada", "inventario")},
            },
        ),
    ]
